apiVersion: v1
kind: PersistentVolume
metadata:
  name: cephfs-charts
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 10Gi
  cephfs:
    monitors:
    - 10.214.160.5:6789
    - 10.214.160.6:6789
    - 10.214.160.7:6789
    path: /kubernetes/charts
    secretRef:
      name: cephfs-secret
    user: admin
  persistentVolumeReclaimPolicy: Retain