apiVersion: v1
kind: Service
metadata:
  name: helm-repo
  namespace: kube-system
  labels:
    app: {{ template "name" . }}
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    kubernetes.io/cluster-service: "true"
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: http
  selector:
    app: {{ template "name" . }}
    release: {{ .Release.Name | quote }}
