apiVersion: v1
kind: Pod
metadata:
  name: {{ template "fullname" . }}
  namespace: default
  labels:
    app: {{ template "name" . }}
    release: {{ .Release.Name }}
spec:
  containers:
  - name: {{ .Chart.Name }}
    image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
    command:
      - sleep
      - "3600"
  restartPolicy: Always